---
title: "Client Report - Weather Delays"
subtitle: "Unit 3 Task 2"
author: "Philip Rosenquist"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_json("https://github.com/byuidatascience/data4missing/raw/master/data-raw/flights_missing/flights_missing.json")
```

## QUESTION 1

1. __Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

_We started with a table that describes the airport's rate of delays and the average time delayed. When ordering the table, we judged that the greatest preference would be to avoid delays to begin with and then to minimize delays. The table below should show this from most preferable results to least preferable._

```{python}
# Include and execute your code here
# find the averages isnted of just making 1500+ to 1500 and find the average insted of -999 becoming np.nan


df = df.fillna(np.nan).replace({"": np.nan, "1500+": "1500", -999 : np.nan, "Febuary": "February"})

report1 = pd.DataFrame(
    data = {"airport name": df["airport_name"],
            "total number of flights": df["num_of_flights_total"],
            "total number of delayed flights": df["num_of_delays_total"],
            "total number of minutes delayed": df["minutes_delayed_total"]
     })

report1 = report1.groupby(["airport name"]).sum()
report1["proportion of delayed flights"] = report1["total number of delayed flights"]/report1["total number of flights"]

report1["average delay time"] = (report1["total number of minutes delayed"]/

report1["total number of delayed flights"])/60

report1 = report1.sort_values(["proportion of delayed flights", "average delay time"])

report1


```

## QUESTION 2

According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “NAS” and “Late-Arriving Aircraft” categories. __Your job is to create a new column that calculates the total number of flights delayed by weather (both severe and mild).__ You will need to replace all the missing values in the Late Aircraft variable with the mean. Show your work by printing the first 5 rows of data in a table. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the Late-Arriving category are due to weather  
    a. From April to August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%  

_Describe your results and analysis here_

```{python}
# Include and execute your code here
report2 = df.copy()
report2 = report2.assign(
    all_weather_delays = lambda x: x.num_of_delays_weather + .3 * x.num_of_delays_late_aircraft + np.where(x.month.isin(["April", "May", "June", "July", "August"]), .4, .65) * x.num_of_delays_nas) 

print(report2)

```

## Question 3

__Using the new weather variable calculated above, create a barplot showing the proportion of all flights that are delayed by weather at each airport. Describe what you learn from this graph.__  

_Describe your results and analysis here_

```{python}

report3 = report2.copy()
report3 = report3.filter(items=["airport_code", "num_of_delays_total", "all_weather_delays"])
report3 = report3.groupby(["airport_code"]).sum()
report3 = report3.assign(
  proportion_of_weather_delays = lambda x: x.num_of_delays_total / x.all_weather_delays
)

print(report3)


```